### ISSUE TITLE
Add generic support for GPS spoofing

### ISSUE THREAD

**Issue by eoudsen** [NetherlandsForensicInstitute/puma#25]
Multiple applications make use of location data to provide functionality within applications.
To use these functionalities it is necessary to set locations to a predetermined place.
To prevent having to add this functionality to every single application that needs it, utility methods can be introduced which can be used by the different applications.
The functionality that should at least be available is:
- Set the location to a specific point
- Set a list of locations in an interval based on a GPX file

Nice to have functionality:
- Stop the setting of locations from a GPX file while it is still updating
- Keeping the location updated at a certain location such that the cache is never outdated

**Comment by btimbermont** [comment]
Currently added features:
* Start simulating a route given a list of points
* Start simulating a route given a GPX file
* Start simulating a route given a start and end location (lookup is done through OSM)
* Pausing the simulated travel (by setting the speed to 0)
* Keeping the location updated at a certain lcoation (same as setting speed to 0)
* Stopping the simulation completely (stop_route)
* Changing the speed manually as the route is being traveled
* Changing the speed automatically within a given range
Features that weren't added:
* Setting a single location once (can be done on any object by calling obj.driver.set_location() )
